// libraries/angular/workspace/projects/chat-ui/src/library/chat-ui.component.ts
import {Component, Input} from '@angular/core';
import {connectApi, loadChatUi} from "chatkitty";

@Component({
  selector: 'ChatUi',
  imports: [],
  template: `
    <div id="chat-ui"></div>
  `,
  standalone: true,
  styles: ``
})
export class ChatUi {

  @Input({required: true}) apiKey: string = "";

  @Input({required: true}) username: string = "";

  @Input({required: true}) widgetId: string = "";


  async ngOnInit() {

    const connection = await connectApi({
      apiKey: this.apiKey,
      username: this.username
    });

    loadChatUi(
      {
        widgetId: this.widgetId,
        container: {height: "100%"},
        audio: {enabled: true},
        components: {
          chat: (_context) => ({
            menuActions: [],
            onMounted: () => {
            },
          })
        },
        templates: {}
      },
      {
        timeout: 50000,
        connection
      }
    );
  }

}

// libraries/vue/src/components/ChatUi.vue
import {connectApi, loadChatUi} from "@chatkitty/core";

<script setup lang="ts">

import {connectApi, loadChatUi} from "@chatkitty/core";

const {apiKey, username, widgetId} = defineProps<{ apiKey: string, username: string, widgetId: string }>()

const initializeChat = async () => {
  const connection = await connectApi({
    apiKey: apiKey,
    username: username
  });

  loadChatUi(
      {
        widgetId: widgetId,
        container: {height: "100%"},
        audio: {enabled: true},
        components: {
          chat: (_context) => ({
            menuActions: [],
            onMounted: () => {
            },
          })
        },
        templates: {}
      },
      {
        timeout: 50000,
        connection
      }
  );
};

initializeChat();


</script>

<template>
  <div id="chat-ui"></div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
