// examples/angular-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ChatUi } from '@chatkitty/angular';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, ChatUi],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular-example';
}

<style>

</style>

<main class="main">
  <div class="root">

    <ChatUi apiKey="afaac908-1db3-4b5c-a7ae-c040b9684403" username="2989c53a-d0c5-4222-af8d-fbf7b0c74ec6"
            widgetId="UWiEkKvdAaUJ1xut"/>
  </div>
</main>


<router-outlet/>

// examples/react-example/src/App.tsx
import './App.css'

import {ChatUi} from '@chatkitty/react'
import '@chatkitty/react/dist/react.css'

function App() {
  return (
    <>
        {/*<ChatUi/>*/}
        <ChatUi apiKey="afaac908-1db3-4b5c-a7ae-c040b9684403" username="2989c53a-d0c5-4222-af8d-fbf7b0c74ec6" widgetId="UWiEkKvdAaUJ1xut"/>
    </>
  )
}

export default App
