// libraries/react/src/components/ChatUi.tsx
import { useEffect } from 'react';
import { loadChatUi, ApiConnection } from '@chatkitty/core';

export type ChatUiProps = {
	widgetId: string;
	username?: string;
	connection?: ApiConnection;
	mode?: "sandbox" | "live";
};

export const ChatUi = ({ widgetId, username, connection, mode }: ChatUiProps) => {
	useEffect(() => {
		if (!username && !connection) return;

		loadChatUi(
			{
				widgetId,
				username,
				container: { height: '100%' },
			},
			{
				...(connection && { connection }),
				mode: mode || "live",
			},
		);
	}, [widgetId, username, connection]);

	return <div id="chat-ui"></div>;
};

// libraries/angular/workspace/projects/chatkitty/src/library/chat-ui.component.ts
import {Component, Input} from '@angular/core';
import { loadChatUi, type ApiConnection } from '@chatkitty/core';

@Component({
  selector: 'ChatUi',
  imports: [],
  template: `
    <div id="chat-ui"></div>
  `,
  standalone: true,
  styles: ``
})
export class ChatUi {

  @Input({required: true}) widgetId: string = "";

  @Input({required: false}) username: string | undefined;

  @Input({required: false}) connection: ApiConnection | undefined;

  @Input({required: false}) mode: ("sandbox" | "live") = "live";


  async ngOnInit() {
    const connection = this.connection;

    loadChatUi(
      {
        widgetId: this.widgetId,
        username: this.username,
        container: { height: "100%" }
      },
      {
        ...(connection && { connection }),
        mode: this.mode || "live",
      }
    );
  }

}
